# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Pragmatic Idealist
subtitle: 静 敬 淡 一
description: To see a world in a grain of sand<br>and a heaven in a wild flower<br>Hold infinity in the palm of your hand<br>and eternity in an hour
author: Chase Liu
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://chaseliu.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:chaseliu/chaseliu.github.io.git
  branch: master

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

# Local search plugin
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# NexT theme config
theme_config:
  social:
    GitHub: https://github.com/chaseliu || github
    Instagram: https://instagram.com/hlycsl || instagram
  social_icons:
    enable: true
    icons_only: false
    transition: true
  footer:
    powered:
      enable: false
      version: false
  favicon:
    small: assets/img/favicon-16x16.png
    medium: assets/img/favicon-32x32.png
    apple_touch_icon: /images/apple-touch-icon.png
  menu:
    home: / || home
    about: /about/ || user
    '{ L & C }': /cnl/ || heart
    tags: /tags/ || tags
    archives: /archives/ || archive
  avatar:
    url: assets/img/avatar.jpg
    rounded: true
    opacity: 1
  pace: false
  pace_theme: pace-theme-loading-bar
